version: "3"

services:
  mysql-svc:
    image: hifrodo/m-dev:django-mysql5.7_v1
    volumes:
      - /work/test3/db/conf:/etc/mysql/conf.d
      - /work/test3/db/data:/var/lib/mysql
    env_file: /work/test3/db/env/.env

  mywas:
    image: hifrodo/m-dev:django-was-docker_v1
    # command: python manage.py runserver 0:8000
    restart: always


  mynginx:
    image: hifrodo/m-dev:nginx_v1
    volumes:
      - /work/test3/nginx/conf:/etc/nginx
      - /work/test3/nginx/log:/var/log/nginx
    ports:
      - "80:80"

